apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: desafio-db
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS nome_do_banco;
    USE nome_do_banco;
    CREATE TABLE IF NOT EXISTS minha_tabela (
      id INT AUTO_INCREMENT PRIMARY KEY,
      nome VARCHAR(255) NOT NULL,
      data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );