apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-js

spec:
  replicas: 2
  selector:
    matchLabels:
      api: app-js
  template:
    metadata:
      labels:
        api: app-js
    spec:
      containers:
        - name: app-js
          image: dadags/app-js:v1
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: 100m 
              memory: 64Mi
            limits:
              cpu: 200m  
              memory: 128Mi