apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: app-js-hpa
  namespace: desafio-api

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-js
  minReplicas: 3
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 2
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 4
          periodSeconds: 60