apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: desafio-db
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: first-storage-class  
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: db-pv