apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: db-pvc
  namespace: app-db

spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: first-pv